name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Confirm static files exist
        run: |
          echo "Listing project files..."
          ls -la
